#Test the confd with ssm by docker-compose in local
version: '2.1'
services:
  haproxy:
    build: .
    volumes:
      - ./confd:/etc/confd
    ports:
      - 3306:3306
      - 3307:3307
      - 9000:9000
    environment:
       AWS_REGION: ChangeMe 
       AWS_ACCESS_KEY_ID: ChangeMe
       AWS_SECRET_ACCESS_KEY: ChangeMe

  mysql_server_1:
    image: mysql 
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE= "db"
      - MYSQL_ROOT_PASSWORD= "pass"
      - MYSQL_USER= "user"
      - MYSQL_PASSWORD= "pass"

  mysql_server_2:
    image: mysql 
    ports:
      - 3305:3306
    environment:
      - MYSQL_DATABASE= "db"
      - MYSQL_ROOT_PASSWORD= "pass"
      - MYSQL_USER= "user"
      - MYSQL_PASSWORD= "pass"

  mysql_master_1:
    image: mysql 
    ports:
      - 3304:3306
    environment:
      - MYSQL_DATABASE= "db"
      - MYSQL_ROOT_PASSWORD= "pass"
      - MYSQL_USER= "user"
      - MYSQL_PASSWORD= "pass"

  mysql_master_2:
    image: mysql 
    ports:
      - 3309:3306
    environment:
      - MYSQL_DATABASE= "db"
      - MYSQL_ROOT_PASSWORD= "pass"
      - MYSQL_USER= "user"
      - MYSQL_PASSWORD= "pass"
